# Generated by Django 4.2.6 on 2023-12-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='monto del servicio', max_digits=10)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.PositiveSmallIntegerField(unique=True)),
                ('telefono', models.CharField(max_length=11)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_desconexion', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='Internet_Valle.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, help_text='costo del servicio', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='monto total del pago', max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='Internet_Valle.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.CharField(max_length=500)),
                ('costo', models.DecimalField(decimal_places=2, help_text='costo', max_digits=10)),
                ('adicional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internet_Valle.adicional')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetalleDePago', to='Internet_Valle.pago')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internet_Valle.equipo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='Internet_Valle.localidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internet_Valle.servicio'),
        ),
    ]
