# Generated by Django 4.2.6 on 2023-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internet_Valle', '0002_remove_servicio_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_desconexion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
